# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 09:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Canales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_canal', models.PositiveSmallIntegerField(choices=[(1, 'Canal de Riego'), (2, 'Canal de Drenaje')])),
                ('nombre_canal', models.CharField(max_length=100)),
                ('logitud', models.DecimalField(decimal_places=3, max_digits=3)),
                ('capacidad', models.DecimalField(decimal_places=0, max_digits=6)),
                ('revestido', models.BooleanField()),
                ('logitudrevestido', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='CoordenadasPredio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.CharField(max_length=50)),
                ('id_lote', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=10)),
                ('met_riego', models.CharField(max_length=30)),
                ('prop', models.CharField(max_length=50)),
                ('fecha_siem', models.CharField(max_length=30)),
                ('code_predi', models.CharField(max_length=254)),
                ('month', models.CharField(max_length=254)),
                ('year', models.IntegerField()),
                ('area_ha', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=21896)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_aguaF1', models.DecimalField(decimal_places=4, max_digits=11)),
                ('consumo_aguaF2', models.DecimalField(decimal_places=4, max_digits=11)),
                ('consumo_aguaF3', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('consumo_aguaF4', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('longitud_raizF1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longitud_raizF2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longitud_raizF3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('longitud_raizF4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaPredioCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('mes', models.SmallIntegerField()),
                ('sem', models.IntegerField()),
                ('area_cultivo', models.DecimalField(decimal_places=4, max_digits=11, validators=[django.core.validators.MinValueValidator(1)])),
                ('Consumo', models.DecimalField(decimal_places=4, max_digits=11)),
                ('lamina', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectorZona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodoriego', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_predi', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=21896, verbose_name='longitude/latitude')),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('codigo_predio', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('cedula_catastral', models.CharField(blank=True, max_length=50, null=True)),
                ('matricula_inmobiliaria', models.CharField(blank=True, max_length=100, null=True)),
                ('area_total', models.DecimalField(decimal_places=4, max_digits=11, validators=[django.core.validators.MinValueValidator(1)])),
                ('area_beneficiada', models.DecimalField(decimal_places=4, max_digits=11, validators=[django.core.validators.MinValueValidator(1)])),
                ('area_cultivada', models.DecimalField(decimal_places=4, max_digits=11, validators=[django.core.validators.MinValueValidator(1)])),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('logitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('nombre_predio', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_predio', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta_escritura', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('ruta_matricula_inmobiliaria', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariomodifica', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioregistro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredioCanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abscisa', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True)),
                ('codigo_predio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.Predio')),
                ('id_canal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.Canales')),
                ('usuario_modifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PCusuariomodifica', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PCusuarioregistro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredioCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_cultivo', models.DecimalField(decimal_places=4, max_digits=11, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True)),
                ('codigo_predio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.Predio')),
            ],
        ),
        migrations.CreateModel(
            name='PredioPropietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derecho', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True)),
                ('codigo_predio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.Predio')),
            ],
        ),
        migrations.CreateModel(
            name='PredioZona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True)),
                ('codigo_predio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.Predio')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=30)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Operador'), (3, 'Consulta')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hore_final', models.TimeField(blank=True, null=True)),
                ('dotacion_inicial', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('dotacion_final', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('volumen_agua', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duracion_riego', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True)),
                ('codigo_predio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.Predio')),
                ('id_canal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.PredioCanal')),
            ],
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('identificacion', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('pirme_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=9)),
                ('celular', models.CharField(blank=True, max_length=12, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=50, null=True)),
                ('identificacion_representante', models.CharField(blank=True, max_length=25, null=True)),
                ('telefono_razon_social', models.CharField(blank=True, max_length=9, null=True)),
                ('celular_razon_social', models.CharField(blank=True, max_length=12, null=True)),
                ('correo_razon_social', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_razon_social', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cultivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('codigo_zona', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre_zona', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Zonausuariomodifica', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Zonausuarioregistro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tercero',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.TipoIdentificacion'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='tipo_identificacion_representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TPRazonSocial', to='SIRICWEB.TipoIdentificacion'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='usuario_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tusuariomodifica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tercero',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tusuarioregistro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroriego',
            name='id_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.TipoCultivo'),
        ),
        migrations.AddField(
            model_name='registroriego',
            name='id_metodoRiego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.MetodoRiego'),
        ),
        migrations.AddField(
            model_name='registroriego',
            name='usuario_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RCusuariomodifica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroriego',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rusuarioregistro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prediozona',
            name='codigo_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.Zonas'),
        ),
        migrations.AddField(
            model_name='prediozona',
            name='usuario_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PZusuariomodifica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prediozona',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PZusuarioregistro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prediopropietario',
            name='identificacion_propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='propietario', to='SIRICWEB.Tercero'),
        ),
        migrations.AddField(
            model_name='prediopropietario',
            name='identificacion_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario', to='SIRICWEB.Tercero'),
        ),
        migrations.AddField(
            model_name='prediopropietario',
            name='usuario_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pusuariomodifica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prediopropietario',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pusuarioregistro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prediocultivo',
            name='id_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.TipoCultivo'),
        ),
        migrations.AddField(
            model_name='prediocultivo',
            name='usuario_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CPusuariomodifica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prediocultivo',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CPusuarioregistro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectorzona',
            name='codigo_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.Zonas'),
        ),
        migrations.AddField(
            model_name='inspectorzona',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectorzona',
            name='usuario_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IZusuariomodifica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectorzona',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IZusuarioregistro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiaprediocultivo',
            name='codigo_predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.Predio'),
        ),
        migrations.AddField(
            model_name='historiaprediocultivo',
            name='id_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.TipoCultivo'),
        ),
        migrations.AddField(
            model_name='historiaprediocultivo',
            name='usuario_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HPCusuariomodifica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiaprediocultivo',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HPCusuarioregistro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='id_cultivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SIRICWEB.TipoCultivo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='usuario_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cusuariomodifica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cusuarioregistro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='registroriego',
            unique_together=set([('codigo_predio', 'id_cultivo', 'fecha_inicio')]),
        ),
        migrations.AlterUniqueTogether(
            name='prediozona',
            unique_together=set([('codigo_predio', 'codigo_zona')]),
        ),
        migrations.AlterUniqueTogether(
            name='prediopropietario',
            unique_together=set([('codigo_predio', 'identificacion_propietario', 'identificacion_usuario')]),
        ),
        migrations.AlterUniqueTogether(
            name='prediocultivo',
            unique_together=set([('codigo_predio', 'id_cultivo')]),
        ),
        migrations.AlterUniqueTogether(
            name='prediocanal',
            unique_together=set([('codigo_predio', 'id_canal', 'abscisa')]),
        ),
        migrations.AlterUniqueTogether(
            name='inspectorzona',
            unique_together=set([('id_usuario', 'codigo_zona')]),
        ),
    ]
