# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
import views
from .views import *

urlpatterns = [
    url(r'^$', login_required(views.HomePageView), name='index'),
	url(r'^registrarUsuarios$', login_required(RegistroUsuario.as_view()), name='registrarUsuarios'),
	url(r'^modificarUsuarios/(?P<pk>\d+)/$', login_required(ModificarUsuario.as_view()), name='modificarUsuarios'),
	url(r'^lista$', login_required(UsuarioList.as_view()), name='usuariolistar'),
	url(r'^contrasena/(?P<id_usuario>\d+)/$', login_required(views.change_password), name='cambiarContrasena'),
	url(r'^datosUsuario/(?P<pk>\d+)/$', login_required(DatosUsuario.as_view()), name='datosUsuario'),
	url(r'^contrasenaUsuario/(?P<id_usuario>\d+)/$', login_required(views.change_password_usuario), name='cambiarContrasenaUsuario'),
	url(r'^registrarTercero$', login_required(RegistroTercero.as_view()), name='registrarTercero'),
	url(r'^listarTerceros$', login_required(TerceroList.as_view()), name='listarTerceros'),
	url(r'^datosTercero.data/', login_required(JSONTerceroList_view), name='datosTercero'),
	url(r'^modificarTerceros/(?P<pk>\d+)/$', login_required(ModificarTercero.as_view()), name='modificarTerceros'),
	url(r'^listarPredios$', login_required(PredioList.as_view()), name='listarPredios'),
	url(r'^registrarPredio$', login_required(RegistroPredio.as_view()), name='registrarPredio'),
	url(r'^modificarPredios/(?P<pk>\w+)/$', login_required(ModificarPredio.as_view()), name='modificarPredios'),
	url(r'^registroPredioPropietario/(?P<codigo_predio>\w+)/$', login_required(views.RegistroPredioPropietario), name='registroPredioPropietario'),
	url(r'^listarTipoIdentificacion$', login_required(TipoIdentificacionList.as_view()), name='listarTipoIdentificacion'),
	url(r'^registrarTipoIdentificacion$', login_required(RegistroTipoIdentificacion.as_view()), name='registrarTipoIdentificacion'),
	url(r'^modificarTipoIdentificacion/(?P<pk>\d+)/$', login_required(ModificarTipoIdentificacion.as_view()), name='modificarTipoIdentificacion'),
	url(r'^eliminarTipoIdentificacion/(?P<pk>\d+)/$', login_required(EliminarTipoIdentificacion.as_view()), name='eliminarTipoIdentificacion'),
	url(r'^listarTipoCultivo$', login_required(TipoCultivoList.as_view()), name='listarTipoCultivo'),
	url(r'^registrarTipoCultivo$', login_required(RegistroTipoCultivo.as_view()), name='registrarTipoCultivo'),
	url(r'^modificarTipoCultivo/(?P<pk>\d+)/$', login_required(ModificarTipoCultivo.as_view()), name='modificarTipoCultivo'),
	url(r'^eliminarTipoCultivo/(?P<pk>\d+)/$', login_required(EliminarTipoCultivo.as_view()), name='eliminarTipoCultivo'),
	url(r'^listarCultivos$', login_required(CultivoList.as_view()), name='listarCultivos'),
	url(r'^registrarCultivo$', login_required(RegistroCultivo.as_view()), name='registrarCultivo'),
	url(r'^modificarCultivo/(?P<pk>\d+)/$', login_required(ModificarCultivo.as_view()), name='modificarCultivo'),
	url(r'^listarCultivos$', login_required(CultivoList.as_view()), name='listarCultivos'),
	url(r'^registrarCultivo$', login_required(RegistroCultivo.as_view()), name='registrarCultivo'),
	url(r'^registroPredioCultivo/(?P<codigo_predio>\w+)/$', login_required(views.RegistroPredioCultivo), name='registroPredioCultivo'),
	url(r'^listarCanales$', login_required(CanalesList.as_view()), name='listarCanales'),
	url(r'^registrarCanales$', login_required(RegistroCanales.as_view()), name='registrarCanales'),
	url(r'^modificarCanales/(?P<pk>\d+)/$', login_required(ModificarCanales.as_view()), name='modificarCanales'),
	url(r'^eliminarCanales/(?P<pk>\d+)/$', login_required(EliminarCanales.as_view()), name='eliminarCanales'),
	url(r'^listarMetodoRiego$', login_required(MetodoRiegoList.as_view()), name='listarMetodoRiego'),
	url(r'^registrarMetodoRiego$', login_required(RegistroMetodoRiego.as_view()), name='registrarMetodoRiego'),
	url(r'^modificarMetodoRiego/(?P<pk>\d+)/$', login_required(ModificarMetodoRiego.as_view()), name='modificarMetodoRiego'),
	url(r'^eliminarMetodoRiego/(?P<pk>\d+)/$', login_required(EliminarMetodoRiego.as_view()), name='eliminarMetodoRiego'),
	url(r'^registroPredioCanal/(?P<codigo_predio>\w+)/$', login_required(views.RegistroPredioCanal), name='registroPredioCanal'),
	url(r'^registroRiego/(?P<codigo_predio>\w+)/$', login_required(views.RegistroRiegoDiario), name='registroRiego'),
	url(r'^modificarRegistroRiego/(?P<pk>\d+)/$', login_required(ModificarRiegoDiario.as_view()), name='modificarRegistroRiego'),
	url(r'^listarPrediosRiego$', login_required(PrediosRiegoList.as_view()), name='listarPrediosRiego'),
	url(r'^datoslistarPrediosRiego.data/', login_required(JSONPrediosRiegoList_view), name='datoslistarPrediosRiego'),
	url(r'^listarRiegosDiario$', login_required(RiegoDiarioList.as_view()), name='listarRiegosDiario'),
	url(r'^points.data/', login_required(points_view), name='points'),
	url(r'^MapaVisor$', login_required(MapaView.as_view()),name='MapaVisor'),
	url(r'^listarHistoriaPredioCultivo/(?P<codigo_predio>\w+)/$', login_required(views.HistoriaPredioCultivoList), name='listarHistoriaPredioCultivo'),
	url(r'^listarHistoriaPredio$', login_required(HistoriaPredioList.as_view()), name='listarHistoriaPredio'),
	url(r'^graficaHistoriaPredioConsumo/(?P<codigo_predio>\w+)/$', login_required(views.GraficaHistoriaPredioConsumo), name='graficaHistoriaPredioConsumo'),
	url(r'^graficaHistoriaConsumo/$', login_required(views.GraficaHistoriaConsumo), name='graficaHistoriaConsumo'),
	url(r'^listarRiegosDiarioPentientes$', login_required(views.RegistroRiegoPendienteList), name='listarRiegosDiarioPentientes'),
	url(r'^datos.data/', login_required(datos_view), name='datos'),
	url(r'^datosHistoriaPredioConsumo.data/(?P<codigo_predio>\w+)/', login_required(jsonhistoriaPredio_view), name='datosHistoriaPredioConsumo'),
	url(r'^listarZonas$', login_required(ZonasList.as_view()), name='listarZonas'),
	url(r'^registrarZonas$', login_required(RegistroZonas.as_view()), name='registrarZonas'),
	url(r'^modificarZonas/(?P<pk>\w+)/$', login_required(ModificarZonas.as_view()), name='modificarZonas'),
	url(r'^eliminarZonas/(?P<pk>\w+)/$', login_required(EliminarZonas.as_view()), name='eliminarZonas'),
	url(r'^listarInspector$', login_required(InpectorList.as_view()), name='listarInspector'),
	url(r'^listarInspectorZona/(?P<id_usuario>\d+)/$', login_required(views.InspectorZonaList), name='listarInspectorZona'),
	url(r'^registroInspectorZona/(?P<id_usuario>\d+)/$', login_required(views.RegistroInspectorZona), name='registroInspectorZona'),
	url(r'^registroPredioZona/(?P<codigo_predio>\w+)/$', login_required(views.RegistroPredioZona), name='registroPredioZona'),
	url(r'^reporteDiarioDotacion/$', login_required(views.ReporteDiarioDotacion), name='reporteDiarioDotacion'),
]

